layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      - CPOA-GPTL
      - loto

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: Benbb96
  # hackerrank: your_username
  instagram: Benbb96
  # keybase: your_username
  linkedin: benjamin-bernard-bouissières-9b1810a7
  # mastodon: your_username
  medium: benbb96
  stackoverflow: 8439435
  # telegram: your_username
  twitter: Benbb96
  # unsplash: your_username
  # vk: your_username
  website: https://www.benbb96.com/
  youtube: Benbb96

topics:
  - name: Python
    web_url: https://www.python.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1024px-Python-logo-notext.svg.png

  - name: Django
    web_url: https://www.djangoproject.com/
    image_url: https://xebialabs.com/wp-content/uploads/2018/10/django-logo.jpg
    
  - name: Processing/P5.js
    web_url: https://processing.org/
    image_url: https://processing.org/img/processing3-logo.png
